name: Zak-Las
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - iniconfig=2.1.0
  - ipykernel=6.29.5
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - libcxx=17.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - pluggy=1.5.0
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pytest=8.4.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - attrs==25.3.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.58.5
      - fsspec==2025.9.0
      - gymnasium==1.2.0
      - idna==3.10
      - imageio==2.37.0
      - ipython==8.12.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - lightning-utilities==0.15.2
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mistune==3.1.4
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - numpy==2.3.1
      - panda==0.3.1
      - pandas==2.3.0
      - pandas-flavor==0.7.0
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - pillow==11.3.0
      - pingouin==0.5.5
      - pipreqs==0.5.0
      - pygame==2.6.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - referencing==0.36.2
      - requests==2.32.4
      - rpds-py==0.27.1
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - soupsieve==2.8
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch==2.8.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - webencodings==0.5.1
      - xarray==2025.9.0
      - yarg==0.1.9

